### ISSUE TITLE
Possibility to iterate over all objects of a repo

### ISSUE THREAD

**Issue by mstuehn** [ostreedev/ostree-rs#38]
Using bare libostree, there is the possibility with `ostree_repo_list_objects` + `g_hash_table_iter_{init,next}` to iterate over all objects in a repo. Is there any equivalent in ostree-rs

**Comment by lucab** [comment]
Thanks for the report.
The underlying low-level binding is available at https://docs.rs/ostree-sys/0.9.1/ostree_sys/fn.ostree_repo_list_objects.html, but the safe wrapper cannot be auto-generated due to the `GHashTable` argument.
For the moment, I think that function will need to be manually wrapped.
If you are going down that route, we'll happily take a PR to host such wrapper (with tests) directly here.

**Comment by mstuehn** [comment]
Unfortunately, implementing this wrapper is beyond my Rust-skills right now :(.

**Comment by mstuehn** [comment]
Issue closed by #39
