### ISSUE TITLE
unclear how to call pull_with_options with the glib/gio version used 

### ISSUE THREAD

**Issue by avrabe** [ostreedev/ostree-rs#5]
I've tried to create a GVariant dictionary with the necessary options being filled.
However, for the "refs" it expects an array of string refs which is not supported in the last official glib-rs version.
What would be the best way to tackle this topic?

**Comment by cgwalters** [comment]
In ostree-rs-ext we are carrying some GVariant helpers because of this, see https://github.com/ostreedev/ostree-rs-ext/blob/460ab2b75585b0edb5cdd5c4883907c9df7faf13/lib/src/variant_utils.rs#L48

Those APIs were recently made public in https://github.com/ostreedev/ostree-rs-ext/pull/19 and we will keep them stable.

Or, perhaps we could move them into this crate.  But have you looked at ostree-rs-ext?

**Comment by cgwalters** [comment]
Though wait, it looks like the latest glib-rs has much improved APIs here, see e.g. https://docs.rs/glib/0.14.0/glib/variant/struct.Variant.html#method.from_array

**Comment by cgwalters** [comment]
Oooh.  Trying out 
```
diff --git a/Cargo.toml b/Cargo.toml
index 3936ab6..ac2f62c 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -34,11 +34,11 @@ members = [".", "sys"]
 [dependencies]
 libc = "0.2"
 bitflags = "1.2.1"
-glib = "0.10.1"
-gio = "0.9.0"
-glib-sys = "0.10.0"
-gobject-sys = "0.10.0"
-gio-sys = "0.10.0"
+glib = "0.14.0"
+gio = "0.14.0"
+glib-sys = "0.14.0"
+gobject-sys = "0.14.0"
+gio-sys = "0.14.0"
 once_cell = "1.4.0"
 ostree-sys = { version = "0.7.3", path = "sys" }
 radix64 = "0.6.2"
```

There's quite a nontrivial amount of porting to do for glib 0.14 in a quick attempt.  And actually doing so will require a semver bump here, which in turn will require semver bump for ostree-rs-ext etc.  But, it looks like a good thing to queue work on.

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree-rs-ext/pull/49 - mind reviewing it?
